all:
  children:
    mikrotik:
      hosts:
        10.0.0.2:
          router_id: "1.1.1.1"
          router_int: "wg2"
        10.0.0.3:
          router_id: "3.3.3.3"
          router_int: "wg0"
      vars:
        ansible_user: admin
        # Я устанавливаю явно, у меня кастомный ключ по-другому не подтягивается :)
        ansible_ssh_private_key_file: ~/.ssh/id_mikrotiks
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: community.routeros.routeros
